"""Run state enum for Interactive QA Buddy."""

from enum import Enum


class RunState(str, Enum):
    """Run state machine states."""
    
    START = "START"
    OPEN_URL = "OPEN_URL"
    SESSION_CHECK = "SESSION_CHECK"
    LOGIN_DETECT = "LOGIN_DETECT"
    WAIT_LOGIN_INPUT = "WAIT_LOGIN_INPUT"
    WAIT_LOGIN_CONFIRM = "WAIT_LOGIN_CONFIRM"
    LOGIN_ATTEMPT = "LOGIN_ATTEMPT"
    POST_LOGIN_VALIDATE = "POST_LOGIN_VALIDATE"
    CONTEXT_DETECT = "CONTEXT_DETECT"
    WAIT_CONTEXT_INPUT = "WAIT_CONTEXT_INPUT"
    DISCOVERY_RUN = "DISCOVERY_RUN"
    DISCOVERY_SUMMARY = "DISCOVERY_SUMMARY"
    WAIT_TEST_INTENT = "WAIT_TEST_INTENT"
    WAIT_TEST_INTENT_MODULE = "WAIT_TEST_INTENT_MODULE"
    TEST_PLAN_BUILD = "TEST_PLAN_BUILD"
    TEST_EXECUTE = "TEST_EXECUTE"
    REPORT_GENERATE = "REPORT_GENERATE"
    DONE = "DONE"
    FAILED = "FAILED"
